/**
 * @copyright © 2020 Copyright ccl
 * @date 2020-11-28
 */

import {ErrnoList as SysErrnoList} from 'bclib/errno';

export class ErrnoList extends SysErrnoList {
	ERR_SIGN_VERIFI_FAIL: ErrnoCode = [100301, `Signature verification failed`]
	ERR_INVALID_MBX_CLIENT_ID: ErrnoCode = [100302, `ERR_INVALID_MBX_CLIENT_ID`]
	ERR_NFT_ASSET_NOT_EXIST: ErrnoCode = [100303, `ERR_NFT_ASSET_NOT_EXIST`]
	ERR_SET_NFT_NOT_PERMISSIONS: ErrnoCode = [100304, `ERR_SET_NFT_NOT_PERMISSIONS`]
	ERR_MBX_CALL_TIMEOUT: ErrnoCode = [100305, `设备调用超时`]
	ERR_MBX_PROXY_REQ_NOT_EXIST: ErrnoCode = [100306, `ERR_MBX_PROXY_REQ_NOT_EXIST`]
	ERR_DUPLICATE_AUTH_NAME: ErrnoCode = [100307, `ERR_DUPLICATE_AUTH_NAME`]
	ERR_NFT_NOT_FOUND: ErrnoCode = [100308, `ERR_NFT_NOT_FOUND`]
	ERR_DOENLOAD_TASK_RUNNING: ErrnoCode = [100309, `ERR_DOENLOAD_TASK_RUNNING`]
	ERR_BAD_DOENLOAD_FILE: ErrnoCode = [100310, `ERR_BAD_DOENLOAD_FILE`]
	ERR_QINIU_UPLOADING_ERR: ErrnoCode = [100311, `ERR_QINIU_UPLOADING`]
	ERR_QINIU_UPLOAD_LIMIT: ErrnoCode = [100312, `ERR_QINIU_UPLOAD_LIMIT`]
	ERR_FILE_NOT_EXISTS_ERR: ErrnoCode = [100313, `ERR_FILE_NOT_EXISTS_ERR`]
	ERR_GRAPHQL_RESULTS: ErrnoCode = [100314, `ERR_GRAPHQL_RESULTS`]
	ERR_NOT_IMPL_ASSET_UNKNOWN: ErrnoCode = [100315, `ERR_NOT_IMPL_ASSET_UNKNOWN`]
	ERR_OPENSEA_GRAPHQL_404: ErrnoCode =  [100316, 'ERR_OPENSEA_GRAPHQL_404']
	ERR_HTTP_STATUS_404: ErrnoCode = [100317, 'ERR_HTTP_STATUS_404']
	ERR_HTTP2_ERROR: ErrnoCode = [100318, `ERR_HTTP2_ERROR`]
	ERR_PHONE_VERIFY_FAIL: ErrnoCode = [100319, `无效的短信验证码`]
	ERR_NO_BSN_WEB3_RPC: ErrnoCode = [100320, `ERR_NO_BSN_WEB3_RPC`]
	ERR_BSN_GREEDY_ERROR: ErrnoCode = [100320, `ERR_BSN_GREEDY_ERROR`, '你太贪心了']
	ERR_SMS_SEND_FREQUENTLY: ErrnoCode = [100321, `每次获取验证码需间隔1分钟以上，请勿频繁操作`, '验证码发送太频繁']
	ERR_SYNC_META_IMAGE_NONE: ErrnoCode = [100322, `ERR_SYNC_META_IMAGE_NONE`]
	ERR_SYNC_META_REAL_NAME: ErrnoCode = [100323, `ERR_SYNC_META_REAL_NAME`]
	ERR_SYNC_META_URI_MIME_ERROR: ErrnoCode = [100324, `ERR_SYNC_META_URI_MIME_ERROR`]
}

export default new ErrnoList;